CFLAGS = -O2
EXEC = ProcNonShareTest ProcShareTest ProcShareTest2 ProcShareTest3 ProcShareSem ProcSemTest ProcMsgTestPwait ProcMsgTestCwait ProcMsgTestCwait2 ProcMsgTestCwait3


all: $(EXEC)

clean:
	rm -f $(EXEC) ProcMsgTestCwait3 *.o *.s *~
